
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install backend dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        cd ..
        pip install -r requirements.txt

    - name: Run backend tests
      run: |
        cd backend
        pytest tests/test_main.py

